version: '3'
services:
  web:
    env_file:
      - .env
    ports:
      - "5000:5000"
  #  environment:
  #- WS_DEFAULT_REGION=${WS_DEFAULT_REGION}
  #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    image: d3v0p5/superup_devops_ch

#healthcheck:
#  test: ["CMD", "curl", "-f", "http://localhost:5000"]
#  interval: 1m30s
#  timeout: 10s
#  retries: 3
#  start_period: 40s
