version: '3'
services:
  web:
    env_file:
      - .env
    ports:
      - "5000:5000"
  #  environment:
  #- WS_DEFAULT_REGION=${WS_DEFAULT_REGION}
  #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    image: superup_ch



          #    build: .
          #    ports:
          #    - "5000:5000"
